name: Deploy koth flask app

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy flask app
    runs-on: ubuntu-latest
    steps:
    - name: Pull changes from master
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.SSHKEY }}
        port: 22
        command: |
          cd koth-python
          git pull origin master
          docker-compose up -d